// Database types - will be auto-generated by Supabase
export type Database = {
  public: {
    Tables: {
      forums: {
        Row: {
          id: string;
          name: string;
          slug: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          created_at?: string;
        };
      };
      threads: {
        Row: {
          id: string;
          forum_id: string;
          user_id: string | null;
          title: string;
          content: string;
          like_count: number; // Legacy - renamed to upvote_count
          upvote_count: number;
          downvote_count: number;
          score?: number;
          is_hidden: boolean;
          is_resource: boolean;
          hidden_at: string | null;
          hidden_until: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          forum_id: string;
          user_id?: string | null;
          title: string;
          content: string;
          like_count?: number;
          upvote_count?: number;
          downvote_count?: number;
          is_hidden?: boolean;
          is_resource?: boolean;
          hidden_at?: string | null;
          hidden_until?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          forum_id?: string;
          user_id?: string | null;
          title?: string;
          content?: string;
          like_count?: number;
          upvote_count?: number;
          downvote_count?: number;
          is_hidden?: boolean;
          is_resource?: boolean;
          hidden_at?: string | null;
          hidden_until?: string | null;
          created_at?: string;
        };
      };
      comments: {
        Row: {
          id: string;
          thread_id: string;
          user_id: string | null;
          content: string;
          like_count: number; // Legacy - renamed to upvote_count
          upvote_count: number;
          downvote_count: number;
          score?: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          thread_id: string;
          user_id?: string | null;
          content: string;
          like_count?: number;
          upvote_count?: number;
          downvote_count?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          thread_id?: string;
          user_id?: string | null;
          content?: string;
          like_count?: number;
          upvote_count?: number;
          downvote_count?: number;
          created_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          username: string;
          avatar_url: string | null;
          bio: string | null;
          website: string | null;
          location: string | null;
          reputation: number;
          is_admin: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username: string;
          avatar_url?: string | null;
          bio?: string | null;
          website?: string | null;
          location?: string | null;
          reputation?: number;
          is_admin?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          username?: string;
          avatar_url?: string | null;
          bio?: string | null;
          website?: string | null;
          location?: string | null;
          reputation?: number;
          is_admin?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      likes: {
        Row: {
          id: string;
          user_id: string;
          thread_id: string | null;
          comment_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          thread_id?: string | null;
          comment_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          thread_id?: string | null;
          comment_id?: string | null;
          created_at?: string;
        };
      };
      superlikes: {
        Row: {
          id: string;
          user_id: string;
          thread_id: string;
          author_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          thread_id: string;
          author_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          thread_id?: string;
          author_id?: string;
          created_at?: string;
        };
      };
    };
  };
};
