// Database types - will be auto-generated by Supabase
export type Database = {
  public: {
    Tables: {
      forums: {
        Row: {
          id: string;
          name: string;
          slug: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          created_at?: string;
        };
      };
      threads: {
        Row: {
          id: string;
          forum_id: string;
          user_id: string | null;
          title: string;
          content: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          forum_id: string;
          user_id?: string | null;
          title: string;
          content: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          forum_id?: string;
          user_id?: string | null;
          title?: string;
          content?: string;
          created_at?: string;
        };
      };
      comments: {
        Row: {
          id: string;
          thread_id: string;
          user_id: string | null;
          content: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          thread_id: string;
          user_id?: string | null;
          content: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          thread_id?: string;
          user_id?: string | null;
          content?: string;
          created_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          username: string;
          avatar_url: string | null;
          is_admin: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username: string;
          avatar_url?: string | null;
          is_admin?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          username?: string;
          avatar_url?: string | null;
          is_admin?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
};
